project:
    name: user-servival-prediction
deployments:
  - name: dev
    executor: celery
    image:
      name: quay.io/astronomer/astro-runtime:12.6.0
    env: dev
    volumes:
      - ./include:/usr/local/airflow/include
